version: "3.6"

volumes:
  postgres:

services:
  nginx:
    container_name: paqmind-nginx
    image: nginx:stable-alpine
    restart: unless-stopped
#    env_file: [.env]
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - next

  next:
    container_name: paqmind-next
    build: ./next
    command: yarn push-dev
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: [.env]
    ports:
      - "3000:3000"
    volumes:
      - ./next/components:/usr/src/app/components
      - ./next/content:/usr/src/app/content
      - ./next/hooks:/usr/src/app/hooks
      - ./next/layout:/usr/src/app/layout
      - ./next/lib:/usr/src/app/lib
      - ./next/pages:/usr/src/app/pages
      - ./next/prisma:/usr/src/app/prisma
      - ./next/public:/usr/src/app/public
      - ./next/styles:/usr/src/app/styles

#  hasura:
#    container_name: paqmind-hasura
#    image: hasura/graphql-engine:v2.9.0
#    ports:
#      - "8080:8080"
#    restart: unless-stopped
#    depends_on:
#      - postgres
#    environment:
#      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
#      HASURA_GRAPHQL_METADATA_DATABASE_URL: ${POSTGRES_DB}
#      PG_DATABASE_URL: ${POSTGRES_DB}
#      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
#      HASURA_GRAPHQL_DEV_MODE: "true"
#      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
#      ## uncomment next line to set an admin secret
#      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  postgres:
    container_name: paqmind-postgres
    image: "postgres:14-alpine"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql
    env_file: [.env]
    environment:
      PGUSER: paqmind
    ports:
      - "5432:5432"



